### ISSUE TITLE
What is the name of this algorithm

### ISSUE THREAD

**Issue by dvberkel** [HAN-ASD-DT/sorting-assignment-luukverberkt#1]
I would like to know the name of this sorting algorithm. Can you find a reference to a description of this algorithm?

**Comment by luukverberkt** [comment]
@dvberkel 

After some googling I would say it looks like the Insertion sort algorithm.
![image](https://user-images.githubusercontent.com/10956654/48416040-6358d980-e74f-11e8-9338-8c957607d19e.png)


The difference between my implementation and what the pictures tells is that i use a seperate Array to store the values instead of switching them earlier in the list.
